### ISSUE TITLE
new_scale_fill() changes colour to previous geom

### ISSUE THREAD

**Issue by mchibok** [eliocamp/ggnewscale#17] opened 2019-07-31 18:24 UTC
I'm trying to plot a spatial heatmap from various x y points that are separed in 2 categories. I wish to plot both categories with `stat_density_2d` in different colors (green and red).

However, whenever I add a `new_scale_fill()`, the background color of previously plotted geom change colors.

For exemple, regular plot:
```
p <- ggplot() +
  aes(long, lat, group = group) +
  geom_polygon(data = hydro.df, fill = "#d9e2ea", color = NA) +
  geom_polygon(data = iles.df, fill = "white", color = NA) +
  geom_path(data = routes.maj.df,
            #aes(long, lat, group = group),
            colour = rgb(0.9, 0.9, 0.9), size = 0.25) +
  geom_polygon(data = villes.df, fill = NA, color = "red", size = 0.2) +
  stat_density_2d(
    data = subset(av.desav, classement == "avantage"),
    aes(x = x, y = y, group = NA, 
      fill = ..level.., alpha = ..level..),
    geom = "polygon") + 
  scale_fill_gradient("< -5 min.",
    low = "white", high = rgb(10, 255, 10, maxColorValue = 255),
    labels = NULL) +
  guides(alpha = F) +
  coord_fixed(ratio = 1, xlim = x.lim, ylim = y.lim, expand = F) +
  theme_void()

plot(p)
```
gives this:
![image](https://user-images.githubusercontent.com/25492081/62236655-8559c100-b39d-11e9-97a5-4cf528c1003f.png)

But when I try to add a scale to plot another stat_density, this is what I get:
```
plot(p + new_scale_fill() #+
  # not plotted
  # stat_density_2d(data = subset(av.desav, classement == "desavantage"),
  #                 aes(x = x, y = y,
  #                     fill = ..level.., alpha = ..level..),
  #                 geom = "polygon") +
  # scale_fill_gradient("> 5 min.",
  #                     low = "white", high = rgb(255,10,10, maxColorValue = 255),
  #                     labels = NULL)
)
```

![image](https://user-images.githubusercontent.com/25492081/62236842-dc5f9600-b39d-11e9-9403-7fe9be5ca3ab.png)

The various geom_polygon data come from shapefiles. I don't know if that could be the problem.
Not sure if it's a bug or something I'm not doing right.

Thanks for your help!

**Comment by eliocamp** [comment] 2019-08-02 18:44
Hi! I think this should be fixed with https://github.com/eliocamp/ggnewscale/issues/16, but I might be wrong on that. Are you using the latest development version? If not, try updating it and see if it works. 

Otherwise, can you get a minimum reproducible example so I can investigate further? Since I don't have the data for your polygons I can't run those :).

**Comment by mchibok** [comment] 2019-08-06 15:10
Hey,
Just updated the version from 0.3.0 to 0.4.0.9 and it works!
Thanks for your help and the package.

**Closed** 2019-08-06 15:10 UTC
