### ISSUE TITLE
Error: Don't know how to add new_scale_color() to a plot

### ISSUE THREAD

**Issue by JonnoB** [eliocamp/ggnewscale#5] opened 2019-03-14 10:11 UTC
I am having trouble getting the package to work as expected. When I run the examples or my own plots I get the following message.

> Error: Don't know how to add new_scale_color() to a plot

I changed "new_scale_color()" to "new_scale("color")" in the example code and got the following message

> Error: Don't know how to add new_scale("color") to a plot
> In addition: Warning messages:
> 1: In get(results[[i]], pos = which(search() == packages[[i]])) :
>   internal error -3 in R_decompress1
> 2: In get(results[[i]], pos = which(search() == packages[[i]])) :
>   internal error -3 in R_decompress1
> 3: In get(results[[i]], pos = which(search() == packages[[i]])) :
>   restarting interrupted promise evaluation
> 4: In get(results[[i]], pos = which(search() == packages[[i]])) :
>   internal error -3 in R_decompress1
> 5: In get(results[[i]], pos = which(search() == packages[[i]])) :
>   restarting interrupted promise evaluation
> 6: In get(results[[i]], pos = which(search() == packages[[i]])) :
>   internal error -3 in R_decompress1
> 7: In mget(objectNames, envir = ns, inherits = TRUE) :
>   internal error -5 in R_decompress1
> 8: In mget(objectNames, envir = ns, inherits = TRUE) :
>   restarting interrupted promise evaluation
> 9: In mget(objectNames, envir = ns, inherits = TRUE) :
>   internal error -5 in R_decompress1

Although this message only appeared the first time I ran the code afterwards it reverted to 

> Error: Don't know how to add new_scale("color") to a plot

I am using R version 3.5.3 and ggplot version 3.1.0. 

Let me know if you need any other information

This package is so helpful, Thanks for putting such effort in!

**Comment by eliocamp** [comment] 2019-03-15 14:50
I think that string of errors indicate that there was some installation problem. I've had similar problems when developing packages and I try to install a modified version of a package that depends on another. Usually restarting the R session solves the problem (Ctrl + Shift + F10 in RStudio). If not, maybe reinstalling the package? 

Please let me know if it works.

**Comment by eliocamp** [comment] 2019-03-21 18:31
@JonnoB are you still having this issue?

**Comment by eliocamp** [comment] 2019-06-27 18:27
Since I was unable to reproduce the problem and you haven't got back to me in 3 months, I'm going to close this issue. I'll reopen it again if you are still having problems.

**Closed by eliocamp** 2019-06-27 18:27 UTC
